### ISSUE TITLE
Cast port to integer

### ISSUE THREAD

**Issue by blakejoy** [selikapro/microservices-python#4]
It may be a Python 3.11 thing ... but it looks like an error gets thrown which in turns returns a 500 internal server error for the auth pod for what I'm assuming is the port here https://github.com/selikapro/microservices-python/blob/4382751315adadbeabd32a69ba9eb8472f37683c/src/auth/server.py#L13.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/9423898/201479001-8f081e88-0c62-40e5-bd5c-5a56a135eecf.png">

**Comment by blakejoy** [comment]
If this doesn't make sense to anyone, we can sync up and debug.

**Comment by berain-uvic** [comment]
I tried that but now I can't connect to the database:
```[2022-11-21 02:51:16,651] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/server.py", line 24, in login
    cur = mysql.connection.cursor()
  File "/usr/local/lib/python3.10/site-packages/flask_mysqldb/__init__.py", line 101, in connection
    ctx.mysql_db = self.connect
  File "/usr/local/lib/python3.10/site-packages/flask_mysqldb/__init__.py", line 88, in connect
    return MySQLdb.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'host.minikube.internal' (115)")
172.17.0.1 - - [21/Nov/2022 02:51:16] "POST /login HTTP/1.1" 500 -
```

**Comment by blakejoy** [comment]
Can you verify that mysql is running in the Docker container?

**Comment by berain-uvic** [comment]
I will look into it! Also, I am using WSL Ubuntu 20.04

**Comment by donwany** [comment]
> 

Should the mysql be running outside the container or inside the container?

**Comment by blakejoy** [comment]
It runs in the docker container iirc

**Comment by donwany** [comment]
> It runs in the docker container iirc

I think I fixed using single quotes '3306' instead of "3306", and then cast it this way:  int(os.environ.get("MYSQL_PORT"))

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: root
  MYSQL_DB: auth
  MYSQL_PORT: '3306'

**Comment by blakejoy** [comment]
> > It runs in the docker container iirc
> 
> I think I fixed it using single quotes '3306' instead of "3306", and then cast it this way: int(os.environ.get("MYSQL_PORT"))
> 
> apiVersion: v1 kind: ConfigMap metadata: name: auth-configmap data: MYSQL_HOST: host.minikube.internal MYSQL_USER: root MYSQL_DB: auth MYSQL_PORT: '3306'

Single and double quotes are the same in Python so it was probably the type casting

**Comment by donwany** [comment]
> 

You are right but in this case the double quote didn't work for me, single worked.

**Comment by berain-uvic** [comment]
> > It runs in the docker container iirc
> 
> I think I fixed it using single quotes '3306' instead of "3306", and then cast it this way: int(os.environ.get("MYSQL_PORT"))
> 
> apiVersion: v1 kind: ConfigMap metadata: name: auth-configmap data: MYSQL_HOST: host.minikube.internal MYSQL_USER: root MYSQL_DB: auth MYSQL_PORT: '3306'

Didn't work for me. I wonder if it has something to do with mysql running locally in WSL...

**Comment by donwany** [comment]
> 

MySQL is running locally

**Comment by berain-uvic** [comment]
Also, it should work if we omit the db port number, as 3306 is the default.

**Comment by berain-uvic** [comment]
Oh well, it was a great tutorial otherwise :) I learned a lot about Kubernetes!

**Comment by donwany** [comment]
well if working it can be closed
